### ISSUE TITLE
Download the googlesheets file 

### ISSUE THREAD

**Issue by cansavvy** [FredHutch/omicsResources-Explorer#3]
https://docs.google.com/spreadsheets/d/1_4VN5MQVPO6KK14mH0P8zBz25s7a-he67qS6Fst6ZTo/edit#gid=288405034

For version control purposes, we will want to save this file. Here's a StackOverflow post that shows how to download it: https://stackoverflow.com/questions/65571739/download-xlsx-file-from-google-drive-in-r 

We can set up a GitHub action that downloads the file every week or so.

**Comment by howardbaik** [comment]
ChatGPT answer:

Downloading a Google Sheet programmatically from a given URL requires making use of the Google Sheets API. In order to automate the downloading of the sheet using a GitHub Action, you would generally do the following:

1. Use the Google Sheets API to download the content.
2. Save the downloaded content in a file.
3. Push the file to your GitHub repository.

However, to download content from Google Sheets using the API, you typically need API credentials, even for public sheets. That being said, I'll guide you through the necessary steps to set this up.

### Step 1: Set Up Google Sheets API

1. Go to the [Google Developers Console](https://console.developers.google.com/).
2. Create a new project.
3. Enable the Google Sheets API for this project.
4. Create credentials (OAuth 2.0 client ID) for a "Desktop App".
5. Download the JSON file containing your credentials.

### Step 2: Add the Credentials to GitHub Secrets

For security, you shouldn't commit your credentials to your repository. Instead, add them as [GitHub Secrets](https://docs.github.com/en/actions/reference/encrypted-secrets).

1. Go to your GitHub repository.
2. Go to the "Settings" tab.
3. In the left sidebar, click on "Secrets".
4. Click "New repository secret".
5. Name the secret something like `SHEETS_API_CREDENTIALS`.
6. Paste the entire content of the JSON file you downloaded from Google Developers Console as the value of the secret.

### Step 3: Create the GitHub Action

Create a new `.yml` file under `.github/workflows/` in your repository.

```yaml
name: Download Google Sheet

on:
  schedule:
    # Runs every week
    - cron: '0 0 * * 0'

jobs:
  download-sheet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        pip install gspread oauth2client

    - name: Download Google Sheet
      env:
        SHEETS_API_CREDENTIALS: ${{ secrets.SHEETS_API_CREDENTIALS }}
      run: |
        python .github/scripts/download_sheet.py

    - name: Commit and Push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Auto-updated Google Sheet" || echo "No changes to commit"
        git push
```

### Step 4: Download Script

Create a Python script at `.github/scripts/download_sheet.py`:

```python
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import json

# Setup the Sheets API
scopes = ['https://spreadsheets.google.com/feeds', 'https://www.googleapis.com/auth/spreadsheets', 'https://www.googleapis.com/auth/drive.file', 'https://www.googleapis.com/auth/drive']

creds_json = json.loads(os.environ.get('SHEETS_API_CREDENTIALS'))
creds = ServiceAccountCredentials.from_json_keyfile_dict(creds_json, scopes)

client = gspread.authorize(creds)

# Open the Google Sheet using its URL
sheet = client.open_by_url('https://docs.google.com/spreadsheets/d/1_4VN5MQVPO6KK14mH0P8zBz25s7a-he67qS6Fst6ZTo/edit?usp=sharing').sheet1

# Get the values from the sheet
values = sheet.get_all_values()

# Save the values in a CSV file
with open('path/to/your/data.csv', 'w') as f:
    writer = csv.writer(f)
    writer.writerows(values)
```

Replace `path/to/your/data.csv` with the path where you want to store the downloaded sheet in your repository.

Now, every week the action will run, download the content of the Google Sheet, and save it in a file in your repository. If there are changes, it will commit and push them.
